/**
 * Per-workspace ephemeral buffer for binary media generated by tools
 * (selfies, video circles) during a single agent turn.
 *
 * Why: tool results are JSON-serialized into the LLM context and persisted
 * into bc_conversation. Putting megabytes of base64 there would burn tokens
 * and bloat the DB. Instead, the tool returns a tiny text-only result like
 * `{ success, scene }`, and stashes the actual bytes here. After the agent
 * turn finishes, the router drains this store and sends each item via the
 * channel adapter (Telegram InputFile / etc.) — then the bytes are gone.
 *
 * One global store, keyed by workspaceId, in-memory only. No persistence.
 */

export type MediaKind = 'photo' | 'video'

export interface PendingMedia {
  kind: MediaKind
  buffer: Buffer
  mimeType: string
  /** Optional caption to send with the media (e.g. brief scene description) */
  caption?: string
}

const store = new Map<string, PendingMedia[]>()

export function pushPendingMedia(workspaceId: string, item: PendingMedia): void {
  const list = store.get(workspaceId) ?? []
  list.push(item)
  store.set(workspaceId, list)
}

export function drainPendingMedia(workspaceId: string): PendingMedia[] {
  const list = store.get(workspaceId) ?? []
  store.delete(workspaceId)
  return list
}

export function clearPendingMedia(workspaceId: string): void {
  store.delete(workspaceId)
}
